L4Re Reference Manual
L4Re - L4 Runtime Environment
L4::Kobject Class Reference
[Kernel Objects]
Base class for all kinds of kernel objects, referred to by capabilities.
Public Member Functions
l4_msgtag_t dec_refcnt (l4_mword_t diff, l4_utcb_t *utcb=l4_utcb())
Decrement the in kernel reference counter for the object.
Protected Member Functions
l4_cap_idx_t cap () const throw ()
Return capability selector.
Friends
template<typename T >
Type_info const * kobject_typeid ()
Get the L4::Type_info for the L4Re interface given in T.
Detailed Description
Base class for all kinds of kernel objects, referred to by capabilities.
#include <l4/sys/capability>
Attention:
Objects derived from Kobject must never add any data to those objects. Kobjects can act only as proxy object for encapsulating object invocations.
Definition at line 451 of file capability.
Member Function Documentation
l4_cap_idx_t L4::Kobject::cap () const throw () [inline, protected]
Return capability selector.
Returns:
Capability selector.
This method is for derived classes to gain access to the actual capability selector.
Definition at line 477 of file capability.
Referenced by L4::Task::add_ku_mem(), L4::Irq::attach(), L4::Icu::bind(), L4::Task::cap_equal(), L4::Task::cap_has_child(), L4::Task::cap_valid(), L4::Irq::chain(), L4::Thread::control(), L4::Factory::create(), L4::Factory::create_factory(), L4::Factory::create_gate(), L4::Factory::create_irq(), L4::Factory::create_task(), L4::Factory::create_thread(), L4::Factory::create_vm(), dec_refcnt(), L4::Task::delete_obj(), L4::Irq::detach(), L4::Thread::ex_regs(), L4::Vcon::get_attr(), L4::Scheduler::idle_time(), L4::Icu::info(), L4::Scheduler::is_online(), L4::Task::map(), L4::Icu::mask(), L4::Thread::modify_senders(), L4::Icu::msi_info(), L4::Vcon::read(), L4::Irq::receive(), L4::Thread::register_del_irq(), L4::Task::release_cap(), L4::Vm::run(), L4::Scheduler::run_thread(), L4::Vcon::send(), L4::Vcon::set_attr(), L4::Icu::set_mode(), L4::Thread::stats_time(), L4::Debugger::switch_log(), L4::Thread::switch_to(), L4::Irq::trigger(), L4::Icu::unbind(), L4::Task::unmap(), L4::Task::unmap_batch(), L4::Icu::unmask(), L4::Irq::unmask(), L4::Thread::vcpu_control(), L4::Thread::vcpu_control_ext(), L4::Thread::vcpu_resume_commit(), L4::Irq::wait(), and L4::Vcon::write().
l4_msgtag_t L4::Kobject::dec_refcnt (l4_mword_t diff, l4_utcb_t * utcb = l4_utcb()) [inline]
Decrement the in kernel reference counter for the object.
Parameters:
diff is the delta that shall be subtracted from the reference count.
utcb is the utcb to use for the invocation.
This function is intended for servers to be able to remove the servers own capability from the counted references. This leads to the semantics that the kernel will delete the object even if the capability of the server is valid. The server can detect the deletion by polling its capabilities or by using the IPC-gate deletion IRQs. And to cleanup if the clients dropped the last reference (capability) to the object.
Definition at line 502 of file capability.
References cap().
Friends And Related Function Documentation
template<typename T > Type_info const* kobject_typeid () [friend]
Get the L4::Type_info for the L4Re interface given in T.
Parameters:
T The type (L4Re interface) for which the information shall be returned.
Returns:
A pointer to the L4::Type_info structure for T.
Reimplemented in L4::Kobject_t< Ipc_gate, Kobject, L4_PROTO_KOBJECT >, L4::Kobject_t< Namespace, L4::Kobject, L4Re::Protocol::Namespace >, L4::Kobject_t< Parent, L4::Kobject, L4Re::Protocol::Parent >, L4::Kobject_t< Irq_eio, Kobject, L4_PROTO_IRQ >, L4::Kobject_t< Factory, Kobject, L4_PROTO_FACTORY >, L4::Kobject_t< Task, Kobject, L4_PROTO_TASK >, L4::Kobject_t< Debug_obj, L4::Kobject, Protocol::Debug >, L4::Kobject_t< Vm, Kobject, L4_PROTO_VM >, L4::Kobject_t< Event, L4::Icu, L4Re::Protocol::Event >, L4::Kobject_t< Rm, L4::Kobject, L4Re::Protocol::Rm >, L4::Kobject_t< Log, L4::Vcon, L4_PROTO_LOG >, L4::Kobject_t< Vcon, Icu, L4_PROTO_LOG >, L4::Kobject_t< Meta, Kobject, L4_PROTO_META >, L4::Kobject_t< Dataspace, L4::Kobject, L4Re::Protocol::Dataspace >, L4::Kobject_t< Vm, Task, L4_PROTO_VM >, L4::Kobject_t< Debugger, Kobject, L4_PROTO_DEBUGGER >, L4::Kobject_t< Mem_alloc, L4::Kobject, L4Re::Protocol::Mem_alloc >, L4::Kobject_t< Thread, Kobject, L4_PROTO_THREAD >, L4::Kobject_t< Irq, Irq_eio, L4_PROTO_IRQ >, L4::Kobject_t< Scheduler, Icu, L4_PROTO_SCHEDULER >, L4::Kobject_t< Icu, Irq_eio, L4_PROTO_IRQ >, and L4::Kobject_t< Goos, L4::Kobject, L4Re::Protocol::Goos >.
Definition at line 87 of file __typeinfo.h.
The documentation for this class was generated from the following file:
l4/sys/capability
L4Re - L4 Runtime Environment