L4Re Reference Manual
L4Re - L4 Runtime Environment
IPC Streams
Functions
L4::Ipc::Istream & operator>> (L4::Ipc::Istream &s, bool &v)
Extract one element of type T from the stream s.
L4::Ipc::Istream & operator>> (L4::Ipc::Istream &s, l4_msgtag_t &v)
Extract the L4 message tag from the stream s.
template<typename T >
L4::Ipc::Istream & operator>> (L4::Ipc::Istream &s, L4::Ipc::Buf_in< T > const &v)
Extract an array of T elements from the stream s.
template<typename T >
L4::Ipc::Istream & operator>> (L4::Ipc::Istream &s, L4::Ipc::Msg_ptr< T > const &v)
Extract an element of type T from the stream s.
template<typename T >
L4::Ipc::Istream & operator>> (L4::Ipc::Istream &s, L4::Ipc::Buf_cp_in< T > const &v)
Extract an array of T elements from the stream s.
L4::Ipc::Ostream & operator<< (L4::Ipc::Ostream &s, bool v)
Insert an element to type T into the stream s.
L4::Ipc::Ostream & operator<< (L4::Ipc::Ostream &s, l4_msgtag_t const &v)
Insert the L4 message tag into the stream s.
template<typename T >
L4::Ipc::Ostream & operator<< (L4::Ipc::Ostream &s, L4::Ipc::Buf_cp_out< T > const &v)
Insert an array with elements of type T into the stream s.
L4::Ipc::Ostream & operator<< (L4::Ipc::Ostream &s, char const *v)
Insert a zero terminated character string into the stream s.
Function Documentation
L4::Ipc::Istream& operator>> (L4::Ipc::Istream & s, bool & v) [inline]
Extract one element of type T from the stream s.
Parameters:
s The stream to extract from.
v Output: extracted value.
Returns:
the stream s.
Definition at line 1240 of file ipc_stream.
References L4::Ipc::Istream::get().
L4::Ipc::Istream& operator>> (L4::Ipc::Istream & s, l4_msgtag_t & v) [inline]
Extract the L4 message tag from the stream s.
Parameters:
s The stream to extract from.
v Output: the extracted tag.
Returns:
the stream s.
Definition at line 1273 of file ipc_stream.
References L4::Ipc::Istream::tag().
template<typename T > L4::Ipc::Istream& operator>> (L4::Ipc::Istream & s, L4::Ipc::Buf_in< T > const & v) [inline]
Extract an array of T elements from the stream s.
This operator actually does not copy out the data in the array, but returns a pointer into the message buffer itself. This means that the data is only valid as long as there is no new data inserted into the stream.
See Ipc::Buf_in, Ipc::Buf_cp_in, and Ipc::Buf_cp_out.
Parameters:
s The stream to extract from.
v Output: pointer to the extracted array (ipc_buf_in()).
Returns:
the stream s.
Definition at line 1295 of file ipc_stream.
References L4::Ipc::Istream::get().
template<typename T > L4::Ipc::Istream& operator>> (L4::Ipc::Istream & s, L4::Ipc::Msg_ptr< T > const & v) [inline]
Extract an element of type T from the stream s.
This operator actually does not copy out the data, but returns a pointer into the message buffer itself. This means that the data is only valid as long as there is no new data inserted into the stream.
See Msg_ptr.
Parameters:
s The stream to extract from.
v Output: pointer to the extracted element.
Returns:
the stream s.
Definition at line 1320 of file ipc_stream.
References L4::Ipc::Istream::get().
template<typename T > L4::Ipc::Istream& operator>> (L4::Ipc::Istream & s, L4::Ipc::Buf_cp_in< T > const & v) [inline]
Extract an array of T elements from the stream s.
This operator does a copy out of the data into the given buffer.
See Ipc::Buf_in, Ipc::Buf_cp_in, and Ipc::Buf_cp_out.
Parameters:
s The stream to extract from.
v buffer description to copy the array to (Ipc::Buf_cp_out()).
Returns:
the stream s.
Definition at line 1341 of file ipc_stream.
References L4::Ipc::Istream::get().
L4::Ipc::Ostream& operator<< (L4::Ipc::Ostream & s, bool v) [inline]
Insert an element to type T into the stream s.
Parameters:
s The stream to insert the element v.
v The element to insert.
Returns:
the stream s.
Definition at line 1359 of file ipc_stream.
References L4::Ipc::Ostream::put().
L4::Ipc::Ostream& operator<< (L4::Ipc::Ostream & s, l4_msgtag_t const & v) [inline]
Insert the L4 message tag into the stream s.
Note:
Only one message tag can be inserted into a stream. Multiple insertions simply overwrite previous insertions.
Parameters:
s The stream to insert the tag v.
v The L4 message tag to insert.
Returns:
the stream s.
Definition at line 1393 of file ipc_stream.
References L4::Ipc::Ostream::tag().
template<typename T > L4::Ipc::Ostream& operator<< (L4::Ipc::Ostream & s, L4::Ipc::Buf_cp_out< T > const & v) [inline]
Insert an array with elements of type T into the stream s.
Parameters:
s The stream to insert the array v.
v The array to insert (see Ipc::Buf_cp_out()).
Returns:
the stream s.
Definition at line 1409 of file ipc_stream.
References L4::Ipc::Buf_cp_out< T >::buf(), L4::Ipc::Ostream::put(), and L4::Ipc::Buf_cp_out< T >::size().
L4::Ipc::Ostream& operator<< (L4::Ipc::Ostream & s, char const * v) [inline]
Insert a zero terminated character string into the stream s.
Parameters:
s The stream to insert the string v.
v The string to insert.
Returns:
the stream s.
This operator produces basically the same content as the array insertion, however the length of the array is calculated using strlen(v) + 1 . The string is copied into the message including the trailing zero.
Definition at line 1430 of file ipc_stream.
References L4::Ipc::Ostream::put().
L4Re - L4 Runtime Environment